export enum Body{
    SEDAN='Sedan',
    COUPE='Coupe',
    SUV='Suv',
    TRUCK='Truck',
    HATCHBACK='HatchBack',
    CONVERTIBLE='Convertible'
}
 
export interface CarAccessories{
    body:'Sedan'|'Coupe'|'SUV'|'Truck'|'HatchBack'|'Convertible',
    seat:number,
    door:number,
    energy:'Petrol'|'Hybird'|'Diesel',
    year:Date,
    transmission:'CVT'|'Manual'|'Automatic',
    driveType:string,
    condition:'used'|'new',
    engineSize:number,
    cylinders:number,
    color:string,
    VIN:string,
    descriptOverview:string,
    physicBody:{
    length:number,
    height:number,
    wheelbase:number,
    height_includeRoofRails:number,
    luggageCapacity_seatUp:number,
    luggageCapacity_seatDown:number,
    width:number,
    width_include_mirrors:number,
    grossVechicleWeight:number,
    maxLoadingWeigt:number,
    maxRoofLoad:number,
    seatMax:number,
    fullTank:number,
    braked:number,
    unBraked:number,
    kerbweight:number,
    turningCircle:number,
    location:[number,number]
   }
}