import { CarDetail } from "src/pages/home/item/typeData";


export const DATA_CAR: CarDetail[] = [
  { 
    brand:'Toyota',
      name: "Toyota Corolla",
      img: "https://via.placeholder.com/300x200",
      script: "Reliable and fuel-efficient sedan",
      speed: "180 km/h",
      energy: "Petrol",
      priceRoot: " 25,000",
      priceBuy: " 20,000",
      status: "Great Price",
      transmission: "Automatic",
      id: 1,
      isUsedTime: "2 years",
      body: "Sedan",
      seat: 5,
      door: 4,
      year: new Date("2022-01-01"),
      driveType: "FWD",
      condition: "used",
      engineSize: 1.8,
      cylinders: 4,
      color: "Silver",
      VIN: "1HGCM82633A123456",
      descriptOverview: "Well-maintained sedan with excellent fuel economy",
      physicBody: {
          length: 4630,
          height: 1435,
          wheelbase: 2700,
          height_includeRoofRails: 1435,
          luggageCapacity_seatUp: 470,
          luggageCapacity_seatDown: 1200,
          width: 1780,
          width_include_mirrors: 2065,
          grossVechicleWeight: 1800,
          maxLoadingWeigt: 400,
          maxRoofLoad: 75,
          seatMax: 5,
          fullTank: 50,
          braked: 1300,
          unBraked: 450,
          kerbweight: 1300,
          turningCircle: 10.8,
          location: [35.6895, 139.6917]
      }
  },
  {
      name: "Honda Civic",
      brand:'Honda',
      img: "https://via.placeholder.com/300x200",
      script: "Sporty and comfortable compact car",
      speed: "190 km/h",
      energy: "Petrol",
      priceRoot: " 28,000",
      priceBuy: " 22,000",
      status: "Sale",
      transmission: "Manual",
      id: 2,
      isUsedTime: "3 years",
      body: "Sedan",
      seat: 5,
      door: 4,
      year: new Date("2021-01-01"),
      driveType: "FWD",
      condition: "used",
      engineSize: 2.0,
      cylinders: 4,
      color: "Red",
      VIN: "2HGES16575H123456",
      descriptOverview: "Sporty sedan with excellent handling characteristics",
      physicBody: {
          length: 4650,
          height: 1415,
          wheelbase: 2735,
          height_includeRoofRails: 1415,
          luggageCapacity_seatUp: 478,
          luggageCapacity_seatDown: 1250,
          width: 1800,
          width_include_mirrors: 2087,
          grossVechicleWeight: 1850,
          maxLoadingWeigt: 410,
          maxRoofLoad: 75,
          seatMax: 5,
          fullTank: 47,
          braked: 1400,
          unBraked: 500,
          kerbweight: 1340,
          turningCircle: 11.0,
          location: [34.0522, -118.2437]
      }
  },
  {
    brand:'Ford',
      name: "Ford Mustang",
      img: "https://via.placeholder.com/300x200",
      script: "Iconic American muscle car",
      speed: "250 km/h",
      energy: "Petrol",
      priceRoot: " 45,000",
      priceBuy: " 35,000",
      status: "none",
      transmission: "Manual",
      id: 3,
      isUsedTime: "1 year",
      body: "Coupe",
      seat: 4,
      door: 2,
      year: new Date("2023-01-01"),
      driveType: "RWD",
      condition: "used",
      engineSize: 5.0,
      cylinders: 8,
      color: "Blue",
      VIN: "1FA6P8CF8L123456",
      descriptOverview: "Powerful muscle car with iconic styling",
      physicBody: {
          length: 4789,
          height: 1381,
          wheelbase: 2720,
          height_includeRoofRails: 1381,
          luggageCapacity_seatUp: 408,
          luggageCapacity_seatDown: 800,
          width: 1916,
          width_include_mirrors: 2081,
          grossVechicleWeight: 2100,
          maxLoadingWeigt: 450,
          maxRoofLoad: 80,
          seatMax: 4,
          fullTank: 61,
          braked: 1600,
          unBraked: 750,
          kerbweight: 1720,
          turningCircle: 12.2,
          location: [42.3314, -83.0458]
      }
  },
  {
      name: "Nissan Leaf",
      brand:'Nissan',
      img: "https://via.placeholder.com/300x200",
      script: "All-electric compact car",
      speed: "150 km/h",
      energy: "Hybird",
      priceRoot: " 35,000",
      priceBuy: " 28,000",
      status: "Great Price",
      transmission: "Automatic",
      id: 4,
      isUsedTime: "2 years",
      body: "HatchBack",
      seat: 5,
      door: 5,
      year: new Date("2022-01-01"),
      driveType: "FWD",
      condition: "used",
      engineSize: 0,
      cylinders: 0,
      color: "White",
      VIN: "1N4AZ1CP8LC123456",
      descriptOverview: "Zero-emission electric vehicle with modern features",
      physicBody: {
          length: 4490,
          height: 1540,
          wheelbase: 2700,
          height_includeRoofRails: 1540,
          luggageCapacity_seatUp: 435,
          luggageCapacity_seatDown: 1160,
          width: 1788,
          width_include_mirrors: 2030,
          grossVechicleWeight: 1995,
          maxLoadingWeigt: 419,
          maxRoofLoad: 75,
          seatMax: 5,
          fullTank: 0,
          braked: 0,
          unBraked: 0,
          kerbweight: 1580,
          turningCircle: 10.6,
          location: [35.4437, 139.6380]
      }
  },
  {
      name: "Volkswagen Polo",
      brand:'Volkswagen',
      img: "https://via.placeholder.com/300x200",
      script: "Affordable and efficient subcompact car",
      speed: "180 km/h",
      energy: "Petrol",
      priceRoot: " 20,000",
      priceBuy: " 16,000",
      status: "Sale",
      transmission: "Manual",
      id: 5,
      isUsedTime: "3 years",
      body: "HatchBack",
      seat: 5,
      door: 5,
      year: new Date("2021-01-01"),
      driveType: "FWD",
      condition: "used",
      engineSize: 1.0,
      cylinders: 3,
      color: "Black",
      VIN: "WVWZZZ6RZLY123456",
      descriptOverview: "Compact and efficient city car with German engineering",
      physicBody: {
          length: 4053,
          height: 1461,
          wheelbase: 2564,
          height_includeRoofRails: 1461,
          luggageCapacity_seatUp: 351,
          luggageCapacity_seatDown: 1125,
          width: 1751,
          width_include_mirrors: 1964,
          grossVechicleWeight: 1680,
          maxLoadingWeigt: 375,
          maxRoofLoad: 75,
          seatMax: 5,
          fullTank: 40,
          braked: 1000,
          unBraked: 580,
          kerbweight: 1105,
          turningCircle: 10.6,
          location: [52.5200, 13.4050]
      }
  },
  {
      name: "BMW 3 Series",
      brand:'BMW',
      img: "https://via.placeholder.com/300x200",
      script: "Luxurious and performance-oriented sedan",
      speed: "240 km/h",
      energy: "Petrol",
      priceRoot: " 45,000",
      priceBuy: " 38,000",
      status: "none",
      transmission: "Automatic",
      id: 6,
      isUsedTime: "1 year",
      body: "Sedan",
      seat: 5,
      door: 4,
      year: new Date("2023-01-01"),
      driveType: "RWD",
      condition: "used",
      engineSize: 2.0,
      cylinders: 4,
      color: "Gray",
      VIN: "WBA5R1C50LFH23456",
      descriptOverview: "Premium sports sedan with cutting-edge technology",
      physicBody: {
          length: 4709,
          height: 1435,
          wheelbase: 2851,
          height_includeRoofRails: 1435,
          luggageCapacity_seatUp: 480,
          luggageCapacity_seatDown: 1300,
          width: 1827,
          width_include_mirrors: 2068,
          grossVechicleWeight: 2150,
          maxLoadingWeigt: 500,
          maxRoofLoad: 75,
          seatMax: 5,
          fullTank: 59,
          braked: 1600,
          unBraked: 750,
          kerbweight: 1545,
          turningCircle: 11.4,
          location: [48.1351, 11.5820]
      }
  },
  {
      name: "Hyundai Kona",
      brand:'Hyundai',
      img: "https://via.placeholder.com/300x200",
      script: "Stylish and practical compact SUV",
      speed: "200 km/h",
      energy: "Petrol",
      priceRoot: " 25,000",
      priceBuy: " 20,000",
      status: "Great Price",
      transmission: "Automatic",
      id: 7,
      isUsedTime: "2 years",
      body: "SUV",
      seat: 5,
      door: 5,
      year: new Date("2022-01-01"),
      driveType: "AWD",
      condition: "used",
      engineSize: 2.0,
      cylinders: 4,
      color: "Orange",
      VIN: "KM8K3CA56LU123456",
      descriptOverview: "Compact SUV with distinctive styling and versatility",
      physicBody: {
          length: 4205,
          height: 1550,
          wheelbase: 2600,
          height_includeRoofRails: 1565,
          luggageCapacity_seatUp: 374,
          luggageCapacity_seatDown: 1156,
          width: 1800,
          width_include_mirrors: 2052,
          grossVechicleWeight: 1930,
          maxLoadingWeigt: 420,
          maxRoofLoad: 80,
          seatMax: 5,
          fullTank: 50,
          braked: 1250,
          unBraked: 600,
          kerbweight: 1383,
          turningCircle: 10.6,
          location: [37.5665, 126.9780]
      }
  },
  {
      name: "Mercedes-Benz C-Class",
      brand:'Mercedes',
      img: "https://via.placeholder.com/300x200",
      script: "Luxurious and refined mid-size sedan",
      speed: "250 km/h",
      energy: "Diesel",
      priceRoot: " 50,000",
      priceBuy: " 42,000",
      status: "Sale",
      transmission: "Automatic",
      id: 8,
      isUsedTime: "3 years",
      body: "Sedan",
      seat: 5,
      door: 4,
      year: new Date("2021-01-01"),
      driveType: "RWD",
      condition: "used",
      engineSize: 2.0,
      cylinders: 4,
      color: "Silver",
      VIN: "WDDWF4KB2LR123456",
      descriptOverview: "Premium luxury sedan with advanced safety features",
      physicBody: {
          length: 4686,
          height: 1442,
          wheelbase: 2840,
          height_includeRoofRails: 1442,
          luggageCapacity_seatUp: 455,
          luggageCapacity_seatDown: 1290,
          width: 1810,
          width_include_mirrors: 2020,
          grossVechicleWeight: 2155,
          maxLoadingWeigt: 460,
          maxRoofLoad: 75,
          seatMax: 5,
          fullTank: 66,
          braked: 1800,
          unBraked: 750,
          kerbweight: 1600,
          turningCircle: 11.1,
          location: [48.7758, 9.1829]
      }
  },


          {
              name: "Subaru Outback",
              brand:'Subaru',
              img: "https://via.placeholder.com/300x200",
              script: "Capable and versatile mid-size crossover",
              speed: "200 km/h",
              energy: "Petrol",
              priceRoot: " 35,000",
              priceBuy: " 28,000",
              status: "none",
              transmission: "Automatic",
              id: 9,
              isUsedTime: "1 year",
              body: "SUV",
              seat: 5,
              door: 5,
              year: new Date("2023-01-01"),
              driveType: "AWD",
              condition: "used",
              engineSize: 2.5,
              cylinders: 4,
              color: "Green",
              VIN: "4S4BTAPC5L3123456",
              descriptOverview: "All-wheel drive wagon with excellent off-road capability",
              physicBody: {
                  length: 4870,
                  height: 1675,
                  wheelbase: 2745,
                  height_includeRoofRails: 1695,
                  luggageCapacity_seatUp: 522,
                  luggageCapacity_seatDown: 1758,
                  width: 1875,
                  width_include_mirrors: 2080,
                  grossVechicleWeight: 2200,
                  maxLoadingWeigt: 485,
                  maxRoofLoad: 80,
                  seatMax: 5,
                  fullTank: 63,
                  braked: 1500,
                  unBraked: 650,
                  kerbweight: 1628,
                  turningCircle: 11.0,
                  location: [35.6762, 139.6503]
              }
          },
          {
              name: "Mazda CX-5",
              brand:'Mazda',
              img: "https://via.placeholder.com/300x200",
              script: "Stylish and fun-to-drive compact SUV",
              speed: "210 km/h",
              energy: "Petrol",
              priceRoot: " 30,000",
              priceBuy: " 24,000",
              status: "Great Price",
              transmission: "Automatic",
              id: 10,
              isUsedTime: "2 years",
              body: "SUV",
              seat: 5,
              door: 5,
              year: new Date("2022-01-01"),
              driveType: "AWD",
              condition: "used",
              engineSize: 2.5,
              cylinders: 4,
              color: "Red",
              VIN: "JM3KFBDM7L0123456",
              descriptOverview: "Premium compact SUV with responsive handling",
              physicBody: {
                  length: 4550,
                  height: 1680,
                  wheelbase: 2700,
                  height_includeRoofRails: 1680,
                  luggageCapacity_seatUp: 442,
                  luggageCapacity_seatDown: 1342,
                  width: 1840,
                  width_include_mirrors: 2115,
                  grossVechicleWeight: 2098,
                  maxLoadingWeigt: 460,
                  maxRoofLoad: 75,
                  seatMax: 5,
                  fullTank: 58,
                  braked: 1800,
                  unBraked: 750,
                  kerbweight: 1550,
                  turningCircle: 11.2,
                  location: [34.6551, 133.9195]
              }
          },
          {
              name: "Chevrolet Silverado",
              brand:'Chevrolet',
              img: "https://via.placeholder.com/300x200",
              script: "Rugged and capable full-size pickup truck",
              speed: "180 km/h",
              energy: "Diesel",
              priceRoot: " 50,000",
              priceBuy: " 40,000",
              status: "Sale",
              transmission: "Automatic",
              id: 11,
              isUsedTime: "3 years",
              body: "Truck",
              seat: 6,
              door: 4,
              year: new Date("2021-01-01"),
              driveType: "4WD",
              condition: "used",
              engineSize: 6.6,
              cylinders: 8,
              color: "Black",
              VIN: "1GCUYGED5MZ123456",
              descriptOverview: "Heavy-duty pickup with impressive towing capacity",
              physicBody: {
                  length: 5885,
                  height: 1918,
                  wheelbase: 3745,
                  height_includeRoofRails: 1918,
                  luggageCapacity_seatUp: 1781,
                  luggageCapacity_seatDown: 1781,
                  width: 2063,
                  width_include_mirrors: 2388,
                  grossVechicleWeight: 3538,
                  maxLoadingWeigt: 1016,
                  maxRoofLoad: 100,
                  seatMax: 6,
                  fullTank: 136,
                  braked: 6350,
                  unBraked: 900,
                  kerbweight: 2522,
                  turningCircle: 14.1,
                  location: [42.3314, -83.0458]
              }
          },
          {
              name: "Kia Sorento",
              brand:'Kia',
              img: "https://via.placeholder.com/300x200",
              script: "Spacious and feature-packed mid-size SUV",
              speed: "190 km/h",
              energy: "Petrol",
              priceRoot: " 35,000",
              priceBuy: " 28,000",
              status: "none",
              transmission: "Automatic",
              id: 12,
              isUsedTime: "1 year",
              body: "SUV",
              seat: 7,
              door: 5,
              year: new Date("2023-01-01"),
              driveType: "AWD",
              condition: "used",
              engineSize: 2.5,
              cylinders: 4,
              color: "White",
              VIN: "5XYPHDA53LG123456",
              descriptOverview: "Family-friendly SUV with third-row seating",
              physicBody: {
                  length: 4810,
                  height: 1700,
                  wheelbase: 2815,
                  height_includeRoofRails: 1720,
                  luggageCapacity_seatUp: 187,
                  luggageCapacity_seatDown: 2011,
                  width: 1900,
                  width_include_mirrors: 2170,
                  grossVechicleWeight: 2550,
                  maxLoadingWeigt: 560,
                  maxRoofLoad: 100,
                  seatMax: 7,
                  fullTank: 67,
                  braked: 2000,
                  unBraked: 750,
                  kerbweight: 1819,
                  turningCircle: 11.4,
                  location: [37.5665, 126.9780]
              }
          },
          {
              name: "Jeep Wrangler",
              brand:'Jeep',
              img: "https://via.placeholder.com/300x200",
              script: "Iconic and off-road capable SUV",
              speed: "170 km/h",
              energy: "Petrol",
              priceRoot: " 40,000",
              priceBuy: " 32,000",
              status: "Great Price",
              transmission: "Manual",
              id: 13,
              isUsedTime: "2 years",
              body: "SUV",
              seat: 4,
              door: 2,
              year: new Date("2022-01-01"),
              driveType: "4WD",
              condition: "used",
              engineSize: 3.6,
              cylinders: 6,
              color: "Green",
              VIN: "1C4HJXAG5MW123456",
              descriptOverview: "Legendary off-road vehicle with removable top",
              physicBody: {
                  length: 4237,
                  height: 1868,
                  wheelbase: 2459,
                  height_includeRoofRails: 1868,
                  luggageCapacity_seatUp: 365,
                  luggageCapacity_seatDown: 898,
                  width: 1875,
                  width_include_mirrors: 2090,
                  grossVechicleWeight: 2268,
                  maxLoadingWeigt: 385,
                  maxRoofLoad: 45,
                  seatMax: 4,
                  fullTank: 66,
                  braked: 1497,
                  unBraked: 750,
                  kerbweight: 1879,
                  turningCircle: 10.36,
                  location: [42.3314, -83.0458]
              }
          },
          {
              name: "Honda Accord",
              brand:'Honda',
              img: "https://via.placeholder.com/300x200",
              script: "Spacious and well-equipped mid-size sedan",
              speed: "210 km/h",
              energy: "Petrol",
              priceRoot: " 30,000",
              priceBuy: " 24,000",
              status: "Sale",
              transmission: "Automatic",
              id: 14,
              isUsedTime: "3 years",
              body: "Sedan",
              seat: 5,
              door: 4,
              year: new Date("2021-01-01"),
              driveType: "FWD",
              condition: "used",
              engineSize: 1.5,
              cylinders: 4,
              color: "Silver",
              VIN: "1HGCV1F34MA123456",
              descriptOverview: "Reliable mid-size sedan with excellent comfort",
              physicBody: {
                  length: 4882,
                  height: 1450,
                  wheelbase: 2830,
                  height_includeRoofRails: 1450,
                  luggageCapacity_seatUp: 473,
                  luggageCapacity_seatDown: 1200,
                  width: 1862,
                  width_include_mirrors: 2110,
                  grossVechicleWeight: 1990,
                  maxLoadingWeigt: 400,
                  maxRoofLoad: 75,
                  seatMax: 5,
                  fullTank: 56,
                  braked: 1000,
                  unBraked: 500,
                  kerbweight: 1490,
                  turningCircle: 11.4,
                  location: [35.6895, 139.6917]
              }
          },
          {
              name: "Toyota Tacoma",
              brand:'Toyota',
              img: "https://via.placeholder.com/300x200",
              script: "Rugged and capable mid-size pickup truck",
              speed: "180 km/h",
              energy: "Petrol",
              priceRoot: " 35,000",
              priceBuy: " 28,000",
              status: "none",
              transmission: "Manual",
              id: 15,
              isUsedTime: "1 year",
              body: "Truck",
              seat: 5,
              door: 4,
              year: new Date("2023-01-01"),
              driveType: "4WD",
              condition: "used",
              engineSize: 3.5,
              cylinders: 6,
              color: "Bronze",
              VIN: "3TMCZ5AN5NM123456",
              descriptOverview: "Mid-size pickup with excellent off-road capabilities",
              physicBody: {
                  length: 5392,
                  height: 1795,
                  wheelbase: 3236,
                  height_includeRoofRails: 1795,
                  luggageCapacity_seatUp: 1520,
                  luggageCapacity_seatDown: 1520,
                  width: 1890,
                  width_include_mirrors: 2160,
                  grossVechicleWeight: 2540,
                  maxLoadingWeigt: 450,
                  maxRoofLoad: 75,
                  seatMax: 5,
                  fullTank: 80,
                  braked: 2900,
                  unBraked: 650,
                  kerbweight: 1985,
                  turningCircle: 12.2,
                  location: [35.6762, 139.6503]
              }
          },
          {
            name: "Chevrolet Camaro",
            brand:'Chevrolet',
            img: "https://via.placeholder.com/300x200",
            script: "High-performance American sports car",
            speed: "250 km/h",
            energy: "Petrol",
            priceRoot: " 55,000",
            priceBuy: " 50,000",
            status: "Sale",
            transmission: "Manual",
            id: 16,
            isUsedTime: "1 year",
            body: "Coupe",
            seat: 4,
            door: 2,
            year: new Date("2023-05-01"),
            driveType: "RWD",
            condition: "used",
            engineSize: 6.2,
            cylinders: 8,
            color: "Yellow",
            VIN: "1G1FH1R72H0145678",
            descriptOverview: "Iconic muscle car with bold design and raw power",
            physicBody: {
                length: 4785,
                height: 1349,
                wheelbase: 2811,
                height_includeRoofRails: 1349,
                luggageCapacity_seatUp: 257,
                luggageCapacity_seatDown: 760,
                width: 1902,
                width_include_mirrors: 2035,
                grossVechicleWeight: 2100,
                maxLoadingWeigt: 430,
                maxRoofLoad: 75,
                seatMax: 4,
                fullTank: 72,
                braked: 1500,
                unBraked: 600,
                kerbweight: 1735,
                turningCircle: 11.5,
                location: [40.7128, -74.0060]
            }
        },
        {
            name: "Tesla Model S",
            brand:'Tesla',
            img: "https://via.placeholder.com/300x200",
            script: "All-electric luxury sedan with exceptional performance",
            speed: "322 km/h",
            energy: "Hybird",
            priceRoot: " 90,000",
            priceBuy: " 85,000",
            status: "Great Price",
            transmission: "Automatic",
            id: 17,
            isUsedTime: "1 year",
            body: "Sedan",
            seat: 5,
            door: 4,
            year: new Date("2023-02-01"),
            driveType: "AWD",
            condition: "new",
            engineSize: 0,
            cylinders: 0,
            color: "White",
            VIN: "5YJSA1E45GF123456",
            descriptOverview: "Premium electric vehicle with cutting-edge technology",
            physicBody: {
                length: 4978,
                height: 1445,
                wheelbase: 2960,
                height_includeRoofRails: 1445,
                luggageCapacity_seatUp: 793,
                luggageCapacity_seatDown: 1795,
                width: 1964,
                width_include_mirrors: 2189,
                grossVechicleWeight: 2590,
                maxLoadingWeigt: 520,
                maxRoofLoad: 80,
                seatMax: 5,
                fullTank: 0,
                braked: 0,
                unBraked: 0,
                kerbweight: 2100,
                turningCircle: 11.1,
                location: [37.7749, -122.4194]
            }
        },
        {
            name: "Audi A4",
            brand:'Audi',
            img: "https://via.placeholder.com/300x200",
            script: "Elegant and reliable German sedan",
            speed: "210 km/h",
            energy: "Petrol",
            priceRoot: " 35,000",
            priceBuy: " 30,000",
            status: "none",
            transmission: "Automatic",
            id: 18,
            isUsedTime: "2 years",
            body: "Sedan",
            seat: 5,
            door: 4,
            year: new Date("2022-06-01"),
            driveType: "FWD",
            condition: "used",
            engineSize: 2.0,
            cylinders: 4,
            color: "Black",
            VIN: "WAUZZZ8K8DA123456",
            descriptOverview: "Smooth ride with advanced technology and comfort",
            physicBody: {
                length: 4762,
                height: 1428,
                wheelbase: 2820,
                height_includeRoofRails: 1428,
                luggageCapacity_seatUp: 480,
                luggageCapacity_seatDown: 1300,
                width: 1842,
                width_include_mirrors: 2020,
                grossVechicleWeight: 2150,
                maxLoadingWeigt: 450,
                maxRoofLoad: 75,
                seatMax: 5,
                fullTank: 58,
                braked: 1500,
                unBraked: 600,
                kerbweight: 1520,
                turningCircle: 11.2,
                location: [52.5200, 13.4050]
            }
        },
        {
            name: "Porsche 911",
            brand:'Porsche',
            img: "https://via.placeholder.com/300x200",
            script: "High-performance sports car with iconic design",
            speed: "300 km/h",
            energy: "Petrol",
            priceRoot: " 120,000",
            priceBuy: " 110,000",
            status: "Sale",
            transmission: "Manual",
            id: 19,
            isUsedTime: "1 year",
            body: "Coupe",
            seat: 4,
            door: 2,
            year: new Date("2023-08-01"),
            driveType: "RWD",
            condition: "new",
            engineSize: 3.0,
            cylinders: 6,
            color: "Silver",
            VIN: "WP0ZZZ99ZTS123456",
            descriptOverview: "Luxury performance car with exceptional handling",
            physicBody: {
                length: 4499,
                height: 1303,
                wheelbase: 2450,
                height_includeRoofRails: 1303,
                luggageCapacity_seatUp: 132,
                luggageCapacity_seatDown: 500,
                width: 1852,
                width_include_mirrors: 1994,
                grossVechicleWeight: 1800,
                maxLoadingWeigt: 430,
                maxRoofLoad: 75,
                seatMax: 4,
                fullTank: 64,
                braked: 1200,
                unBraked: 500,
                kerbweight: 1600,
                turningCircle: 10.6,
                location: [48.8566, 2.3522]
            }
        },
        {
            name: "Toyota Prius",
            brand:'Toyota',
            img: "https://via.placeholder.com/300x200",
            script: "Efficient hybrid car with a focus on fuel economy",
            speed: "180 km/h",
            energy: "Hybird",
            priceRoot: " 25,000",
            priceBuy: " 20,000",
            status: "Great Price",
            transmission: "Automatic",
            id: 20,
            isUsedTime: "3 years",
            body: "HatchBack",
            seat: 5,
            door: 5,
            year: new Date("2021-01-01"),
            driveType: "FWD",
            condition: "used",
            engineSize: 1.8,
            cylinders: 4,
            color: "Blue",
            VIN: "JTDKB20U987654321",
            descriptOverview: "Reliable hybrid vehicle with outstanding fuel economy",
            physicBody: {
                length: 4575,
                height: 1490,
                wheelbase: 2700,
                height_includeRoofRails: 1490,
                luggageCapacity_seatUp: 455,
                luggageCapacity_seatDown: 1200,
                width: 1760,
                width_include_mirrors: 1964,
                grossVechicleWeight: 1820,
                maxLoadingWeigt: 400,
                maxRoofLoad: 50,
                seatMax: 5,
                fullTank: 45,
                braked: 1100,
                unBraked: 500,
                kerbweight: 1360,
                turningCircle: 10.8,
                location: [35.6895, 139.6917]
            }
        },
        {
            name: "Mercedes-Benz GLC",
            brand:'Mercedes',
            img: "https://via.placeholder.com/300x200",
            script: "Luxury compact SUV with advanced features",
            speed: "230 km/h",
            energy: "Diesel",
            priceRoot: " 65,000",
            priceBuy: " 60,000",
            status: "none",
            transmission: "Automatic",
            id: 21,
            isUsedTime: "1 year",
            body: "SUV",
            seat: 5,
            door: 5,
            year: new Date("2023-01-01"),
            driveType: "AWD",
            condition: "new",
            engineSize: 2.2,
            cylinders: 4,
            color: "Black",
            VIN: "WDC0G4JB5KV123456",
            descriptOverview: "Comfortable and versatile SUV with premium features",
            physicBody: {
                length: 4658,
                height: 1644,
                wheelbase: 2873,
                height_includeRoofRails: 1644,
                luggageCapacity_seatUp: 550,
                luggageCapacity_seatDown: 1600,
                width: 1890,
                width_include_mirrors: 2077,
                grossVechicleWeight: 2480,
                maxLoadingWeigt: 450,
                maxRoofLoad: 100,
                seatMax: 5,
                fullTank: 66,
                braked: 1600,
                unBraked: 750,
                kerbweight: 1735,
                turningCircle: 11.8,
                location: [50.1109, 8.6821]
            }
        },  {
          name: "Chevrolet Corvette",
          brand:'Chevrolet',
          img: "https://via.placeholder.com/300x200",
          script: "American sports car with excellent performance",
          speed: "296 km/h",
          energy: "Petrol",
          priceRoot: " 60,000",
          priceBuy: " 55,000",
          status: "Sale",
          transmission: "Automatic",
          id: 22,
          isUsedTime: "2 years",
          body: "Coupe",
          seat: 2,
          door: 2,
          year: new Date("2021-09-01"),
          driveType: "RWD",
          condition: "used",
          engineSize: 6.2,
          cylinders: 8,
          color: "Red",
          VIN: "1G1YY26U775123456",
          descriptOverview: "Powerful and sleek coupe with iconic styling",
          physicBody: {
              length: 4631,
              height: 1235,
              wheelbase: 2710,
              height_includeRoofRails: 1235,
              luggageCapacity_seatUp: 286,
              luggageCapacity_seatDown: 680,
              width: 1933,
              width_include_mirrors: 2098,
              grossVechicleWeight: 2000,
              maxLoadingWeigt: 440,
              maxRoofLoad: 75,
              seatMax: 2,
              fullTank: 70,
              braked: 1400,
              unBraked: 500,
              kerbweight: 1545,
              turningCircle: 11.6,
              location: [34.0522, -118.2437]
          }
      },
      {
          name: "Ford Mustang",
          brand:'Ford',
          img: "https://via.placeholder.com/300x200",
          script: "Classic American muscle car with modern upgrades",
          speed: "250 km/h",
          energy: "Petrol",
          priceRoot: " 50,000",
          priceBuy: " 45,000",
          status: "Great Price",
          transmission: "Manual",
          id: 23,
          isUsedTime: "3 years",
          body: "Coupe",
          seat: 4,
          door: 2,
          year: new Date("2020-07-01"),
          driveType: "RWD",
          condition: "used",
          engineSize: 5.0,
          cylinders: 8,
          color: "Blue",
          VIN: "1FA6P8TH3K5100000",
          descriptOverview: "Stylish and powerful coupe with a retro touch",
          physicBody: {
              length: 4789,
              height: 1375,
              wheelbase: 2720,
              height_includeRoofRails: 1375,
              luggageCapacity_seatUp: 380,
              luggageCapacity_seatDown: 900,
              width: 1915,
              width_include_mirrors: 2024,
              grossVechicleWeight: 2100,
              maxLoadingWeigt: 420,
              maxRoofLoad: 60,
              seatMax: 4,
              fullTank: 59,
              braked: 1600,
              unBraked: 600,
              kerbweight: 1675,
              turningCircle: 11.8,
              location: [36.1627, -86.7816]
          }
      },
  
      // Body type: Sedan
      {
          name: "Honda Accord",
          brand:'Honda',
          img: "https://via.placeholder.com/300x200",
          script: "Reliable and spacious mid-size sedan",
          speed: "220 km/h",
          energy: "Petrol",
          priceRoot: " 30,000",
          priceBuy: " 27,000",
          status: "none",
          transmission: "Automatic",
          id: 24,
          isUsedTime: "1 year",
          body: "Sedan",
          seat: 5,
          door: 4,
          year: new Date("2023-01-01"),
          driveType: "FWD",
          condition: "new",
          engineSize: 2.0,
          cylinders: 4,
          color: "Gray",
          VIN: "1HGCV1F1XMA000000",
          descriptOverview: "Comfortable sedan with a focus on reliability",
          physicBody: {
              length: 4901,
              height: 1450,
              wheelbase: 2830,
              height_includeRoofRails: 1450,
              luggageCapacity_seatUp: 470,
              luggageCapacity_seatDown: 1300,
              width: 1862,
              width_include_mirrors: 2024,
              grossVechicleWeight: 2300,
              maxLoadingWeigt: 460,
              maxRoofLoad: 50,
              seatMax: 5,
              fullTank: 55,
              braked: 1300,
              unBraked: 500,
              kerbweight: 1580,
              turningCircle: 11.3,
              location: [40.7128, -74.0060]
          }
      },
      {
          name: "BMW 3 Series",
          brand:"BMW",
          img: "https://via.placeholder.com/300x200",
          script: "Compact luxury sedan with sporty feel",
          speed: "240 km/h",
          energy: "Petrol",
          priceRoot: " 40,000",
          priceBuy: " 38,000",
          status: "Sale",
          transmission: "Automatic",
          id: 25,
          isUsedTime: "2 years",
          body: "Sedan",
          seat: 5,
          door: 4,
          year: new Date("2022-01-01"),
          driveType: "RWD",
          condition: "used",
          engineSize: 2.0,
          cylinders: 4,
          color: "White",
          VIN: "WBA8E5G51GNT000000",
          descriptOverview: "Sophisticated sedan with sporty handling and luxury",
          physicBody: {
              length: 4709,
              height: 1445,
              wheelbase: 2851,
              height_includeRoofRails: 1445,
              luggageCapacity_seatUp: 500,
              luggageCapacity_seatDown: 1200,
              width: 1827,
              width_include_mirrors: 2024,
              grossVechicleWeight: 2100,
              maxLoadingWeigt: 420,
              maxRoofLoad: 75,
              seatMax: 5,
              fullTank: 59,
              braked: 1500,
              unBraked: 500,
              kerbweight: 1545,
              turningCircle: 11.3,
              location: [48.1351, 11.5820]
          }
      },
  
      // Body type: HatchBack
      {
          name: "Ford Fiesta",
          brand:'Ford',

          img: "https://via.placeholder.com/300x200",
          script: "Compact and efficient hatchback for city driving",
          speed: "180 km/h",
          energy: "Petrol",
          priceRoot: " 20,000",
          priceBuy: " 18,000",
          status: "Great Price",
          transmission: "Manual",
          id: 26,
          isUsedTime: "3 years",
          body: "HatchBack",
          seat: 5,
          door: 5,
          year: new Date("2020-08-01"),
          driveType: "FWD",
          condition: "used",
          engineSize: 1.5,
          cylinders: 4,
          color: "Blue",
          VIN: "3FADP4EJ8KM000000",
          descriptOverview: "Economical car with versatile design and small footprint",
          physicBody: {
              length: 4068,
              height: 1476,
              wheelbase: 2493,
              height_includeRoofRails: 1476,
              luggageCapacity_seatUp: 310,
              luggageCapacity_seatDown: 1150,
              width: 1735,
              width_include_mirrors: 1900,
              grossVechicleWeight: 1675,
              maxLoadingWeigt: 450,
              maxRoofLoad: 50,
              seatMax: 5,
              fullTank: 42,
              braked: 1100,
              unBraked: 500,
              kerbweight: 1165,
              turningCircle: 10.2,
              location: [51.509865, -0.118092]
          }
      },
      {
          name: "Volkswagen Golf",
          brand:'Volkswagen',

          img: "https://via.placeholder.com/300x200",
          script: "Well-rounded compact car with European engineering",
          speed: "210 km/h",
          energy: "Diesel",
          priceRoot: " 25,000",
          priceBuy: " 23,000",
          status: "none",
          transmission: "Automatic",
          id: 27,
          isUsedTime: "2 years",
          body: "HatchBack",
          seat: 5,
          door: 5,
          year: new Date("2021-10-01"),
          driveType: "FWD",
          condition: "used",
          engineSize: 2.0,
          cylinders: 4,
          color: "Black",
          VIN: "WVWZZZAUZHW000000",
          descriptOverview: "Compact hatchback with impressive versatility and style",
          physicBody: {
              length: 4284,
              height: 1492,
              wheelbase: 2636,
              height_includeRoofRails: 1492,
              luggageCapacity_seatUp: 380,
              luggageCapacity_seatDown: 1250,
              width: 1789,
              width_include_mirrors: 2042,
              grossVechicleWeight: 1800,
              maxLoadingWeigt: 400,
              maxRoofLoad: 75,
              seatMax: 5,
              fullTank: 50,
              braked: 1200,
              unBraked: 550,
              kerbweight: 1350,
              turningCircle: 10.9,
              location: [48.8588443, 2.2943506]
          }
      },
      {
        name: "Audi TT",
        brand:'Audi',
        img: "https://via.placeholder.com/300x200",
        script: "Compact sports coupe with iconic design",
        speed: "250 km/h",
        energy: "Petrol",
        priceRoot: "40,000",
        priceBuy: "37,000",
        status: "none",
        transmission: "Automatic",
        id: 28,
        isUsedTime: "1 year",
        body: "Coupe",
        seat: 4,
        door: 2,
        year: new Date("2022-03-01"),
        driveType: "AWD",
        condition: "new",
        engineSize: 2.5,
        cylinders: 5,
        color: "Yellow",
        VIN: "WAUZZZ8J3EA123456",
        descriptOverview: "Sleek design with advanced tech features",
        physicBody: {
            length: 4191,
            height: 1353,
            wheelbase: 2505,
            height_includeRoofRails: 1353,
            luggageCapacity_seatUp: 305,
            luggageCapacity_seatDown: 712,
            width: 1832,
            width_include_mirrors: 1940,
            grossVechicleWeight: 1710,
            maxLoadingWeigt: 380,
            maxRoofLoad: 60,
            seatMax: 4,
            fullTank: 55,
            braked: 1300,
            unBraked: 500,
            kerbweight: 1450,
            turningCircle: 10.9,
            location: [52.5200, 13.4050]
        }
    },
    {
        name: "Mercedes-Benz AMG GT",
        brand:'Mercedes',
        img: "https://via.placeholder.com/300x200",
        script: "High-performance luxury coupe",
        speed: "310 km/h",
        energy: "Petrol",
        priceRoot: "120,000",
        priceBuy: "115,000",
        status: "Sale",
        transmission: "Automatic",
        id: 29,
        isUsedTime: "3 years",
        body: "Coupe",
        seat: 2,
        door: 2,
        year: new Date("2019-10-01"),
        driveType: "RWD",
        condition: "used",
        engineSize: 4.0,
        cylinders: 8,
        color: "Silver",
        VIN: "WDDYK7HA7KA123456",
        descriptOverview: "Luxurious sports coupe with impressive speed",
        physicBody: {
            length: 4546,
            height: 1283,
            wheelbase: 2630,
            height_includeRoofRails: 1283,
            luggageCapacity_seatUp: 285,
            luggageCapacity_seatDown: 710,
            width: 1939,
            width_include_mirrors: 2055,
            grossVechicleWeight: 1895,
            maxLoadingWeigt: 405,
            maxRoofLoad: 55,
            seatMax: 2,
            fullTank: 75,
            braked: 1450,
            unBraked: 600,
            kerbweight: 1625,
            turningCircle: 11.3,
            location: [48.8566, 2.3522]
        }
    },
    {
        name: "Porsche 718 Cayman",
        brand:"Porsche",
        img: "https://via.placeholder.com/300x200",
        script: "Stylish coupe with powerful performance",
        speed: "275 km/h",
        energy: "Petrol",
        priceRoot: "60,000",
        priceBuy: "57,000",
        status: "Great Price",
        transmission: "Manual",
        id: 30,
        isUsedTime: "2 years",
        body: "Coupe",
        seat: 2,
        door: 2,
        year: new Date("2021-06-01"),
        driveType: "RWD",
        condition: "used",
        engineSize: 2.0,
        cylinders: 4,
        color: "White",
        VIN: "WP0ZZZ98ZKS123456",
        descriptOverview: "Agile and well-balanced for thrilling drives",
        physicBody: {
            length: 4379,
            height: 1295,
            wheelbase: 2475,
            height_includeRoofRails: 1295,
            luggageCapacity_seatUp: 425,
            luggageCapacity_seatDown: 895,
            width: 1801,
            width_include_mirrors: 1915,
            grossVechicleWeight: 1750,
            maxLoadingWeigt: 390,
            maxRoofLoad: 50,
            seatMax: 2,
            fullTank: 64,
            braked: 1500,
            unBraked: 600,
            kerbweight: 1450,
            turningCircle: 10.8,
            location: [40.7128, -74.0060]
        }
    },

    // Body type: Sedan
    {
        name: "Toyota Camry",
        brand:'Toyota',

        img: "https://via.placeholder.com/300x200",
        script: "Spacious and reliable sedan",
        speed: "210 km/h",
        energy: "Petrol",
        priceRoot: "28,000",
        priceBuy: "25,500",
        status: "Great Price",
        transmission: "Automatic",
        id: 31,
        isUsedTime: "1 year",
        body: "Sedan",
        seat: 5,
        door: 4,
        year: new Date("2022-05-01"),
        driveType: "FWD",
        condition: "new",
        engineSize: 2.5,
        cylinders: 4,
        color: "Gray",
        VIN: "4T1BF1FK5GU123456",
        descriptOverview: "Reliable mid-size sedan with a comfortable interior",
        physicBody: {
            length: 4881,
            height: 1455,
            wheelbase: 2825,
            height_includeRoofRails: 1455,
            luggageCapacity_seatUp: 510,
            luggageCapacity_seatDown: 1320,
            width: 1840,
            width_include_mirrors: 1980,
            grossVechicleWeight: 2050,
            maxLoadingWeigt: 460,
            maxRoofLoad: 50,
            seatMax: 5,
            fullTank: 60,
            braked: 1500,
            unBraked: 500,
            kerbweight: 1575,
            turningCircle: 11.1,
            location: [34.0522, -118.2437]
        }
    },
    {
        name: "Nissan Altima",
        brand:'Nissan',
        img: "https://via.placeholder.com/300x200",
        script: "Mid-size sedan with advanced safety features",
        speed: "220 km/h",
        energy: "Petrol",
        priceRoot: "26,000",
        priceBuy: "23,500",
        status: "none",
        transmission: "Automatic",
        id: 32,
        isUsedTime: "2 years",
        body: "Sedan",
        seat: 5,
        door: 4,
        year: new Date("2021-04-01"),
        driveType: "AWD",
        condition: "used",
        engineSize: 2.5,
        cylinders: 4,
        color: "Black",
        VIN: "1N4BL4BV0LC123456",
        descriptOverview: "Economical sedan with spacious interior and comfort",
        physicBody: {
            length: 4893,
            height: 1466,
            wheelbase: 2825,
            height_includeRoofRails: 1466,
            luggageCapacity_seatUp: 508,
            luggageCapacity_seatDown: 1335,
            width: 1850,
            width_include_mirrors: 2020,
            grossVechicleWeight: 2100,
            maxLoadingWeigt: 450,
            maxRoofLoad: 60,
            seatMax: 5,
            fullTank: 61,
            braked: 1500,
            unBraked: 520,
            kerbweight: 1620,
            turningCircle: 11.4,
            location: [51.5074, -0.1278]
        }
    },
    {
        name: "Hyundai Sonata",
        brand:"Hyundai",
        img: "https://via.placeholder.com/300x200",
        script: "Affordable sedan with sleek design",
        speed: "230 km/h",
        energy: "Petrol",
        priceRoot: "29,000",
        priceBuy: "26,000",
        status: "Sale",
        transmission: "Automatic",
        id: 33,
        isUsedTime: "3 years",
        body: "Sedan",
        seat: 5,
        door: 4,
        year: new Date("2020-08-01"),
        driveType: "FWD",
        condition: "used",
        engineSize: 2.4,
        cylinders: 4,
        color: "Blue",
        VIN: "5NPE24AF0FH123456",
        descriptOverview: "Stylish sedan with premium features at an affordable price",
        physicBody: {
            length: 4855,
            height: 1450,
            wheelbase: 2800,
            height_includeRoofRails: 1450,
            luggageCapacity_seatUp: 510,
            luggageCapacity_seatDown: 1350,
            width: 1830,
            width_include_mirrors: 1995,
            grossVechicleWeight: 2050,
            maxLoadingWeigt: 470,
            maxRoofLoad: 55,
            seatMax: 5,
            fullTank: 60,
            braked: 1500,
            unBraked: 500,
            kerbweight: 1610,
            turningCircle: 11.0,
            location: [41.8781, -87.6298]
        }
    },
    {
      name: "Volkswagen Golf",
      brand:'Volkswagen',
      img: "https://via.placeholder.com/300x200",
      script: "Compact hatchback with advanced tech",
      speed: "200 km/h",
      energy: "Petrol",
      priceRoot: "25,000",
      priceBuy: "22,000",
      status: "Great Price",
      transmission: "Automatic",
      id: 34,
      isUsedTime: "1 year",
      body: "HatchBack",
      seat: 5,
      door: 5,
      year: new Date("2022-02-01"),
      driveType: "FWD",
      condition: "new",
      engineSize: 1.4,
      cylinders: 4,
      color: "Blue",
      VIN: "WVWZZZ1KZAW123456",
      descriptOverview: "Compact yet powerful, with modern infotainment system",
      physicBody: {
          length: 4284,
          height: 1456,
          wheelbase: 2620,
          height_includeRoofRails: 1480,
          luggageCapacity_seatUp: 380,
          luggageCapacity_seatDown: 1270,
          width: 1789,
          width_include_mirrors: 2027,
          grossVechicleWeight: 1880,
          maxLoadingWeigt: 450,
          maxRoofLoad: 70,
          seatMax: 5,
          fullTank: 55,
          braked: 1500,
          unBraked: 620,
          kerbweight: 1350,
          turningCircle: 10.6,
          location: [52.3676, 4.9041]
      }
  },
  {
      name: "Ford Focus",
      brand:'Ford',

      img: "https://via.placeholder.com/300x200",
      script: "Stylish hatchback with spacious interior",
      speed: "215 km/h",
      energy: "Diesel",
      priceRoot: "24,000",
      priceBuy: "21,000",
      status: "Sale",
      transmission: "Manual",
      id: 35,
      isUsedTime: "2 years",
      body: "HatchBack",
      seat: 5,
      door: 5,
      year: new Date("2021-01-01"),
      driveType: "FWD",
      condition: "used",
      engineSize: 2.0,
      cylinders: 4,
      color: "White",
      VIN: "1FAHP3N21CL123456",
      descriptOverview: "Advanced safety features with eco-friendly diesel engine",
      physicBody: {
          length: 4360,
          height: 1469,
          wheelbase: 2649,
          height_includeRoofRails: 1490,
          luggageCapacity_seatUp: 375,
          luggageCapacity_seatDown: 1250,
          width: 1825,
          width_include_mirrors: 2047,
          grossVechicleWeight: 1820,
          maxLoadingWeigt: 420,
          maxRoofLoad: 60,
          seatMax: 5,
          fullTank: 53,
          braked: 1450,
          unBraked: 610,
          kerbweight: 1380,
          turningCircle: 11.1,
          location: [40.4168, -3.7038]
      }
  },
  {
      name: "Mazda 3 Hatchback",
      brand:'Mazda',
      img: "https://via.placeholder.com/300x200",
      script: "Premium compact hatchback with smooth handling",
      speed: "210 km/h",
      energy: "Petrol",
      priceRoot: "28,000",
      priceBuy: "24,000",
      status: "none",
      transmission: "Automatic",
      id: 36,
      isUsedTime: "3 years",
      body: "HatchBack",
      seat: 5,
      door: 5,
      year: new Date("2020-05-01"),
      driveType: "AWD",
      condition: "used",
      engineSize: 2.5,
      cylinders: 4,
      color: "Gray",
      VIN: "JM1BPADM0L1134567",
      descriptOverview: "Excellent handling and luxurious interior",
      physicBody: {
          length: 4460,
          height: 1440,
          wheelbase: 2725,
          height_includeRoofRails: 1475,
          luggageCapacity_seatUp: 360,
          luggageCapacity_seatDown: 1290,
          width: 1795,
          width_include_mirrors: 2025,
          grossVechicleWeight: 1840,
          maxLoadingWeigt: 430,
          maxRoofLoad: 65,
          seatMax: 5,
          fullTank: 51,
          braked: 1400,
          unBraked: 600,
          kerbweight: 1390,
          turningCircle: 10.8,
          location: [35.6895, 139.6917]
      }
  },

  // Body type: Convertible
  {
      name: "BMW Z4",
      brand:'BMW',
      img: "https://via.placeholder.com/300x200",
      script: "Luxurious convertible with thrilling performance",
      speed: "240 km/h",
      energy: "Petrol",
      priceRoot: "50,000",
      priceBuy: "47,000",
      status: "Great Price",
      transmission: "Automatic",
      id: 37,
      isUsedTime: "1 year",
      body: "Convertible",
      seat: 2,
      door: 2,
      year: new Date("2022-07-01"),
      driveType: "RWD",
      condition: "new",
      engineSize: 2.0,
      cylinders: 4,
      color: "Red",
      VIN: "WBADN63400GH123456",
      descriptOverview: "Sporty convertible with top-notch performance",
      physicBody: {
          length: 4324,
          height: 1304,
          wheelbase: 2470,
          height_includeRoofRails: 1304,
          luggageCapacity_seatUp: 281,
          luggageCapacity_seatDown: 835,
          width: 1864,
          width_include_mirrors: 2042,
          grossVechicleWeight: 1810,
          maxLoadingWeigt: 360,
          maxRoofLoad: 45,
          seatMax: 2,
          fullTank: 52,
          braked: 1300,
          unBraked: 570,
          kerbweight: 1455,
          turningCircle: 10.5,
          location: [48.1351, 11.5820]
      }
  },
  {
      name: "Audi A5 Cabriolet",
      brand:'Audi',
      img: "https://via.placeholder.com/300x200",
      script: "Elegant convertible with cutting-edge technology",
      speed: "235 km/h",
      energy: "Petrol",
      priceRoot: "55,000",
      priceBuy: "51,000",
      status: "Sale",
      transmission: "Automatic",
      id: 38,
      isUsedTime: "2 years",
      body: "Convertible",
      seat: 4,
      door: 2,
      year: new Date("2021-08-01"),
      driveType: "AWD",
      condition: "used",
      engineSize: 2.0,
      cylinders: 4,
      color: "Black",
      VIN: "WAUYGAFC3HN123456",
      descriptOverview: "Stylish and versatile, ideal for open-air drives",
      physicBody: {
          length: 4673,
          height: 1383,
          wheelbase: 2765,
          height_includeRoofRails: 1383,
          luggageCapacity_seatUp: 320,
          luggageCapacity_seatDown: 900,
          width: 1846,
          width_include_mirrors: 2020,
          grossVechicleWeight: 2070,
          maxLoadingWeigt: 420,
          maxRoofLoad: 50,
          seatMax: 4,
          fullTank: 58,
          braked: 1500,
          unBraked: 600,
          kerbweight: 1600,
          turningCircle: 11.4,
          location: [45.4642, 9.1900]
      }
  },
  {
      name: "Mercedes-Benz C-Class Cabriolet",
      brand:'Mercedes',
      img: "https://via.placeholder.com/300x200",
      script: "Premium convertible with luxurious features",
      speed: "250 km/h",
      energy: "Petrol",
      priceRoot: "62,000",
      priceBuy: "58,000",
      status: "Great Price",
      transmission: "Automatic",
      id: 39,
      isUsedTime: "1 year",
      body: "Convertible",
      seat: 4,
      door: 2,
      year: new Date("2022-06-01"),
      driveType: "RWD",
      condition: "new",
      engineSize: 3.0,
      cylinders: 6,
      color: "Silver",
      VIN: "WDDWK4KB1HF123456",
      descriptOverview: "Luxurious comfort with a powerful engine",
      physicBody: {
          length: 4686,
          height: 1401,
          wheelbase: 2840,
          height_includeRoofRails: 1401,
          luggageCapacity_seatUp: 285,
          luggageCapacity_seatDown: 875,
          width: 1810,
          width_include_mirrors: 2007,
          grossVechicleWeight: 2120,
          maxLoadingWeigt: 460,
          maxRoofLoad: 60,
          seatMax: 4,
          fullTank: 59,
          braked: 1550,
          unBraked: 610,
          kerbweight: 1700,
          turningCircle: 11.2,
          location: [51.1657, 10.4515]
      }
  },
  {
    name: "Ford F-150",
    brand:'Ford',
    img: "https://via.placeholder.com/300x200",
    script: "Reliable truck with impressive towing capacity",
    speed: "180 km/h",
    energy: "Petrol",
    priceRoot: "30,000",
    priceBuy: "28,000",
    status: "Great Price",
    transmission: "Automatic",
    id: 40,
    isUsedTime: "1 year",
    body: "Truck",
    seat: 5,
    door: 4,
    year: new Date("2022-03-01"),
    driveType: "4WD",
    condition: "new",
    engineSize: 3.5,
    cylinders: 6,
    color: "Blue",
    VIN: "1FTEW1E44KFC12345",
    descriptOverview: "Best-selling truck with advanced safety features",
    physicBody: {
        length: 5885,
        height: 1918,
        wheelbase: 3620,
        height_includeRoofRails: 1923,
        luggageCapacity_seatUp: 1325,
        luggageCapacity_seatDown: 2100,
        width: 2029,
        width_include_mirrors: 2270,
        grossVechicleWeight: 3200,
        maxLoadingWeigt: 900,
        maxRoofLoad: 100,
        seatMax: 5,
        fullTank: 136,
        braked: 3500,
        unBraked: 750,
        kerbweight: 2500,
        turningCircle: 7.5,
        location: [37.7749, -122.4194]
    }
},
{
    name: "Ram 1500",
    brand:'Ram Trucks',
    img: "https://via.placeholder.com/300x200",
    script: "Powerful truck with luxurious interior options",
    speed: "190 km/h",
    energy: "Diesel",
    priceRoot: "35,000",
    priceBuy: "32,000",
    status: "Sale",
    transmission: "Automatic",
    id: 41,
    isUsedTime: "2 years",
    body: "Truck",
    seat: 5,
    door: 4,
    year: new Date("2021-06-01"),
    driveType: "4WD",
    condition: "used",
    engineSize: 3.0,
    cylinders: 6,
    color: "Black",
    VIN: "1C6RR7FT0LS123456",
    descriptOverview: "Versatile truck ideal for both work and leisure",
    physicBody: {
        length: 5944,
        height: 1965,
        wheelbase: 3683,
        height_includeRoofRails: 1970,
        luggageCapacity_seatUp: 1360,
        luggageCapacity_seatDown: 2335,
        width: 2029,
        width_include_mirrors: 2270,
        grossVechicleWeight: 3250,
        maxLoadingWeigt: 890,
        maxRoofLoad: 100,
        seatMax: 5,
        fullTank: 121,
        braked: 3900,
        unBraked: 800,
        kerbweight: 2370,
        turningCircle: 8.1,
        location: [34.0522, -118.2437]
    }
},
{
    name: "Chevrolet Silverado 1500",
    brand:'Chevrolet',

    img: "https://via.placeholder.com/300x200",
    script: "Durable truck with high payload capacity",
    speed: "185 km/h",
    energy: "Petrol",
    priceRoot: "28,000",
    priceBuy: "26,000",
    status: "none",
    transmission: "Automatic",
    id: 42,
    isUsedTime: "3 years",
    body: "Truck",
    seat: 6,
    door: 4,
    year: new Date("2020-01-01"),
    driveType: "RWD",
    condition: "used",
    engineSize: 5.3,
    cylinders: 8,
    color: "Silver",
    VIN: "1GCUYBEF4LZ123456",
    descriptOverview: "Robust and reliable for heavy-duty tasks",
    physicBody: {
        length: 5884,
        height: 1930,
        wheelbase: 3685,
        height_includeRoofRails: 1935,
        luggageCapacity_seatUp: 1220,
        luggageCapacity_seatDown: 2600,
        width: 2060,
        width_include_mirrors: 2270,
        grossVechicleWeight: 3200,
        maxLoadingWeigt: 950,
        maxRoofLoad: 100,
        seatMax: 6,
        fullTank: 98,
        braked: 4000,
        unBraked: 800,
        kerbweight: 2325,
        turningCircle: 7.8,
        location: [40.7128, -74.0060]
    }
},
{
    name: "Toyota Tundra",
    brand:'Toyota',
    img: "https://via.placeholder.com/300x200",
    script: "Rugged truck built for durability and performance",
    speed: "175 km/h",
    energy: "Petrol",
    priceRoot: "42,000",
    priceBuy: "39,000",
    status: "Great Price",
    transmission: "Automatic",
    id: 43,
    isUsedTime: "1 year",
    body: "Truck",
    seat: 5,
    door: 4,
    year: new Date("2022-09-01"),
    driveType: "4WD",
    condition: "new",
    engineSize: 5.7,
    cylinders: 8,
    color: "White",
    VIN: "5TFDW5F17AX123456",
    descriptOverview: "Versatile and capable of handling tough terrains",
    physicBody: {
        length: 5885,
        height: 1900,
        wheelbase: 3626,
        height_includeRoofRails: 1905,
        luggageCapacity_seatUp: 1486,
        luggageCapacity_seatDown: 2400,
        width: 2029,
        width_include_mirrors: 2270,
        grossVechicleWeight: 3400,
        maxLoadingWeigt: 950,
        maxRoofLoad: 100,
        seatMax: 5,
        fullTank: 98,
        braked: 4500,
        unBraked: 900,
        kerbweight: 2550,
        turningCircle: 8.5,
        location: [34.0522, -118.2437]
    }
},
{
    name: "Nissan Titan",
    brand:'Nissan',
    img: "https://via.placeholder.com/300x200",
    script: "Sturdy truck with exceptional towing capabilities",
    speed: "185 km/h",
    energy: "Petrol",
    priceRoot: "38,000",
    priceBuy: "34,000",
    status: "Sale",
    transmission: "Automatic",
    id: 44,
    isUsedTime: "2 years",
    body: "Truck",
    seat: 5,
    door: 4,
    year: new Date("2021-02-01"),
    driveType: "4WD",
    condition: "used",
    engineSize: 5.6,
    cylinders: 8,
    color: "Gray",
    VIN: "1N6AA1E53MN123456",
    descriptOverview: "Combines strength and luxury for a perfect driving experience",
    physicBody: {
        length: 5948,
        height: 1802,
        wheelbase: 3700,
        height_includeRoofRails: 1807,
        luggageCapacity_seatUp: 1344,
        luggageCapacity_seatDown: 2178,
        width: 2060,
        width_include_mirrors: 2270,
        grossVechicleWeight: 3300,
        maxLoadingWeigt: 800,
        maxRoofLoad: 100,
        seatMax: 5,
        fullTank: 98,
        braked: 4700,
        unBraked: 900,
        kerbweight: 2530,
        turningCircle: 7.7,
        location: [36.1627, -86.7816]
    }
},

// Body type: SUV
{
    name: "Toyota RAV4",
    brand:'Toyota',
    img: "https://via.placeholder.com/300x200",
    script: "Compact SUV with excellent fuel economy",
    speed: "180 km/h",
    energy: "Petrol",
    priceRoot: "28,000",
    priceBuy: "25,000",
    status: "Great Price",
    transmission: "Automatic",
    id: 45,
    isUsedTime: "1 year",
    body: "SUV",
    seat: 5,
    door: 5,
    year: new Date("2022-11-01"),
    driveType: "AWD",
    condition: "new",
    engineSize: 2.5,
    cylinders: 4,
    color: "Red",
    VIN: "2T3F1RFV6NW123456",
    descriptOverview: "Versatile and spacious for urban and off-road adventures",
    physicBody: {
        length: 4600,
        height: 1685,
        wheelbase: 2690,
        height_includeRoofRails: 1690,
        luggageCapacity_seatUp: 580,
        luggageCapacity_seatDown: 1690,
        width: 1845,
        width_include_mirrors: 2070,
        grossVechicleWeight: 2250,
        maxLoadingWeigt: 750,
        maxRoofLoad: 90,
        seatMax: 5,
        fullTank: 55,
        braked: 1500,
        unBraked: 750,
        kerbweight: 1575,
        turningCircle: 5.6,
        location: [34.0522, -118.2437]
    }
},
{
    name: "Honda CR-V",
    brand:'Honda',
    img: "https://via.placeholder.com/300x200",
    script: "Spacious and efficient compact SUV",
    speed: "185 km/h",
    energy: "Petrol",
    priceRoot: "30,000",
    priceBuy: "27,000",
    status: "none",
    transmission: "Automatic",
    id: 46,
    isUsedTime: "2 years",
    body: "SUV",
    seat: 5,
    door: 5,
    year: new Date("2021-08-01"),
    driveType: "AWD",
    condition: "used",
    engineSize: 1.5,
    cylinders: 4,
    color: "White",
    VIN: "2HKRW2H58MH123456",
    descriptOverview: "Comfortable ride with advanced safety features",
    physicBody: {
        length: 4590,
        height: 1689,
        wheelbase: 2660,
        height_includeRoofRails: 1695,
        luggageCapacity_seatUp: 522,
        luggageCapacity_seatDown: 1600,
        width: 1855,
        width_include_mirrors: 2080,
        grossVechicleWeight: 2200,
        maxLoadingWeigt: 850,
        maxRoofLoad: 85,
        seatMax: 5,
        fullTank: 57,
        braked: 1500,
        unBraked: 680,
        kerbweight: 1560,
        turningCircle: 5.5,
        location: [40.7128, -74.0060]
    }
},
{
    name: "Ford Explorer",
    brand:'Ford',
    img: "https://via.placeholder.com/300x200",
    script: "Mid-size SUV with spacious interior",
    speed: "190 km/h",
    energy: "Petrol",
    priceRoot: "35,000",
    priceBuy: "32,000",
    status: "Sale",
    transmission: "Automatic",
    id: 47,
    isUsedTime: "1 year",
    body: "SUV",
    seat: 7,
    door: 5,
    year: new Date("2022-05-01"),
    driveType: "AWD",
    condition: "new",
    engineSize: 3.0,
    cylinders: 6,
    color: "Blue",
    VIN: "1FM5K8D89NGA12345",
    descriptOverview: "Perfect for families and adventurous trips",
    physicBody: {
        length: 5030,
        height: 1785,
        wheelbase: 3025,
        height_includeRoofRails: 1790,
        luggageCapacity_seatUp: 525,
        luggageCapacity_seatDown: 2476,
        width: 2004,
        width_include_mirrors: 2225,
        grossVechicleWeight: 2900,
        maxLoadingWeigt: 850,
        maxRoofLoad: 100,
        seatMax: 7,
        fullTank: 72,
        braked: 2700,
        unBraked: 760,
        kerbweight: 2180,
        turningCircle: 6.1,
        location: [34.0522, -118.2437]
    }
},
{
    name: "Chevrolet Equinox",
    brand:'Chevrolet',
    img: "https://via.placeholder.com/300x200",
    script: "Stylish SUV with a comfortable interior",
    speed: "180 km/h",
    energy: "Petrol",
    priceRoot: "28,000",
    priceBuy: "25,500",
    status: "Great Price",
    transmission: "Automatic",
    id: 48,
    isUsedTime: "2 years",
    body: "SUV",
    seat: 5,
    door: 5,
    year: new Date("2021-09-01"),
    driveType: "AWD",
    condition: "used",
    engineSize: 1.5,
    cylinders: 4,
    color: "Silver",
    VIN: "2GNAXHEV3J6201234",
    descriptOverview: "Compact SUV with a sporty design and efficiency",
    physicBody: {
        length: 4655,
        height: 1685,
        wheelbase: 2725,
        height_includeRoofRails: 1690,
        luggageCapacity_seatUp: 1060,
        luggageCapacity_seatDown: 1810,
        width: 1843,
        width_include_mirrors: 2070,
        grossVechicleWeight: 2150,
        maxLoadingWeigt: 850,
        maxRoofLoad: 85,
        seatMax: 5,
        fullTank: 60,
        braked: 1500,
        unBraked: 750,
        kerbweight: 1560,
        turningCircle: 5.8,
        location: [36.1627, -86.7816]
    }
},
{
    name: "Hyundai Tucson",
    brand:'Hyundai',
    img: "https://via.placeholder.com/300x200",
    script: "Modern SUV with excellent safety ratings",
    speed: "175 km/h",
    energy: "Petrol",
    priceRoot: "30,000",
    priceBuy: "28,000",
    status: "none",
    transmission: "Automatic",
    id: 49,
    isUsedTime: "1 year",
    body: "SUV",
    seat: 5,
    door: 5,
    year: new Date("2022-04-01"),
    driveType: "AWD",
    condition: "new",
    engineSize: 2.0,
    cylinders: 4,
    color: "Gray",
    VIN: "5NMJ73AF3NH123456",
    descriptOverview: "Stylish and practical, perfect for everyday use",
    physicBody: {
        length: 4480,
        height: 1650,
        wheelbase: 2670,
        height_includeRoofRails: 1655,
        luggageCapacity_seatUp: 620,
        luggageCapacity_seatDown: 1750,
        width: 1850,
        width_include_mirrors: 2080,
        grossVechicleWeight: 2200,
        maxLoadingWeigt: 800,
        maxRoofLoad: 90,
        seatMax: 5,
        fullTank: 62,
        braked: 1600,
        unBraked: 730,
        kerbweight: 1600,
        turningCircle: 5.5,
        location: [37.7749, -122.4194]
    }
},
{
  name: "Toyota RAV4",
  brand:"Toyota",
  img: "https://via.placeholder.com/300x200",
  script: "Compact SUV with excellent reliability",
  speed: "180 km/h",
  energy: "Petrol",
  priceRoot: "30,000",
  priceBuy: "28,000",
  status: "Great Price",
  transmission: "Automatic",
  id: 50,
  isUsedTime: "1 year",
  body: "SUV",
  seat: 5,
  door: 5,
  year: new Date("2022-05-01"),
  driveType: "AWD",
  condition: "new",
  engineSize: 2.5,
  cylinders: 4,
  color: "Red",
  VIN: "2T3F1RFV6NW123456",
  descriptOverview: "Versatile and spacious for urban and off-road adventures",
  physicBody: {
      length: 4600,
      height: 1685,
      wheelbase: 2690,
      height_includeRoofRails: 1690,
      luggageCapacity_seatUp: 580,
      luggageCapacity_seatDown: 1690,
      width: 1845,
      width_include_mirrors: 2070,
      grossVechicleWeight: 2250,
      maxLoadingWeigt: 750,
      maxRoofLoad: 90,
      seatMax: 5,
      fullTank: 55,
      braked: 1500,
      unBraked: 750,
      kerbweight: 1575,
      turningCircle: 5.6,
      location: [34.0522, -118.2437]
  }
},
{
  name: "Honda CR-V",
  brand:'Honda',
  img: "https://via.placeholder.com/300x200",
  script: "Spacious and efficient compact SUV",
  speed: "185 km/h",
  energy: "Petrol",
  priceRoot: "30,000",
  priceBuy: "27,000",
  status: "none",
  transmission: "Automatic",
  id: 51,
  isUsedTime: "2 years",
  body: "SUV",
  seat: 5,
  door: 5,
  year: new Date("2021-08-01"),
  driveType: "AWD",
  condition: "used",
  engineSize: 1.5,
  cylinders: 4,
  color: "White",
  VIN: "2HKRW2H58MH123456",
  descriptOverview: "Comfortable ride with advanced safety features",
  physicBody: {
      length: 4590,
      height: 1689,
      wheelbase: 2660,
      height_includeRoofRails: 1695,
      luggageCapacity_seatUp: 522,
      luggageCapacity_seatDown: 1600,
      width: 1855,
      width_include_mirrors: 2080,
      grossVechicleWeight: 2200,
      maxLoadingWeigt: 850,
      maxRoofLoad: 85,
      seatMax: 5,
      fullTank: 57,
      braked: 1500,
      unBraked: 680,
      kerbweight: 1560,
      turningCircle: 5.5,
      location: [40.7128, -74.0060]
  }
},
{
  name: "Ford Explorer",
  brand:'Ford',
  img: "https://via.placeholder.com/300x200",
  script: "Mid-size SUV with spacious interior",
  speed: "190 km/h",
  energy: "Petrol",
  priceRoot: "35,000",
  priceBuy: "32,000",
  status: "Sale",
  transmission: "Automatic",
  id: 52,
  isUsedTime: "1 year",
  body: "SUV",
  seat: 7,
  door: 5,
  year: new Date("2022-05-01"),
  driveType: "AWD",
  condition: "new",
  engineSize: 3.0,
  cylinders: 6,
  color: "Blue",
  VIN: "1FM5K8D89NGA12345",
  descriptOverview: "Perfect for families and adventurous trips",
  physicBody: {
      length: 5030,
      height: 1785,
      wheelbase: 3025,
      height_includeRoofRails: 1790,
      luggageCapacity_seatUp: 525,
      luggageCapacity_seatDown: 2476,
      width: 2004,
      width_include_mirrors: 2225,
      grossVechicleWeight: 2900,
      maxLoadingWeigt: 850,
      maxRoofLoad: 100,
      seatMax: 7,
      fullTank: 72,
      braked: 2700,
      unBraked: 760,
      kerbweight: 2180,
      turningCircle: 6.1,
      location: [34.0522, -118.2437]
  }
},
{
  name: "Chevrolet Equinox",
  brand:"Chevrolet",
  img: "https://via.placeholder.com/300x200",
  script: "Stylish SUV with a comfortable interior",
  speed: "180 km/h",
  energy: "Petrol",
  priceRoot: "28,000",
  priceBuy: "25,500",
  status: "Great Price",
  transmission: "Automatic",
  id: 53,
  isUsedTime: "2 years",
  body: "SUV",
  seat: 5,
  door: 5,
  year: new Date("2021-09-01"),
  driveType: "AWD",
  condition: "used",
  engineSize: 1.5,
  cylinders: 4,
  color: "Silver",
  VIN: "2GNAXHEV3J6201234",
  descriptOverview: "Compact SUV with a sporty design and efficiency",
  physicBody: {
      length: 4655,
      height: 1685,
      wheelbase: 2725,
      height_includeRoofRails: 1690,
      luggageCapacity_seatUp: 1060,
      luggageCapacity_seatDown: 1810,
      width: 1843,
      width_include_mirrors: 2070,
      grossVechicleWeight: 2150,
      maxLoadingWeigt: 850,
      maxRoofLoad: 85,
      seatMax: 5,
      fullTank: 60,
      braked: 1500,
      unBraked: 750,
      kerbweight: 1560,
      turningCircle: 5.8,
      location: [36.1627, -86.7816]
  }
},
{
  name: "Hyundai Tucson",
  brand:'Hyundai',
  img: "https://via.placeholder.com/300x200",
  script: "Modern SUV with excellent safety ratings",
  speed: "175 km/h",
  energy: "Petrol",
  priceRoot: "30,000",
  priceBuy: "28,000",
  status: "none",
  transmission: "Automatic",
  id: 0,
  isUsedTime: "1 year",
  body: "SUV",
  seat: 5,
  door: 5,
  year: new Date("2022-04-01"),
  driveType: "AWD",
  condition: "new",
  engineSize: 2.0,
  cylinders: 4,
  color: "Gray",
  VIN: "5NMJ73AF3NH123456",
  descriptOverview: "Stylish and practical, perfect for everyday use",
  physicBody: {
      length: 4480,
      height: 1650,
      wheelbase: 2670,
      height_includeRoofRails: 1655,
      luggageCapacity_seatUp: 620,
      luggageCapacity_seatDown: 1750,
      width: 1850,
      width_include_mirrors: 2080,
      grossVechicleWeight: 2200,
      maxLoadingWeigt: 800,
      maxRoofLoad: 90,
      seatMax: 5,
      fullTank: 62,
      braked: 1600,
      unBraked: 730,
      kerbweight: 1600,
      turningCircle: 5.5,
      location: [37.7749, -122.4194]
  }
}
      ];